# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            reflection
tagline:          'another coding blog'
description:      'Learning, cheatsheets, tips, computer engineering related topics.'
url:              https://vlasebian.github.io
baseurl:          https://vlasebian.github.io/

paginate:         5

# Custom variables

