# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            reflection
tagline:          'coding blog'
description:      'Lorem ipsum, lorem ipsum, lorem ipsum'
url:              https://vlasebian.github.io
baseurl:          https://vlasebian.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
