# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            reflection
#tagline:          'another random blog.'
description:      'another random blog.'
url:              https://vlasebian.github.io
baseurl:          https://vlasebian.github.io/

paginate:         5

# Custom variables
version:          1.0.0
